/** Catalog entries are independent pages. parent identifies a relationship, not a route. */
export const projects = [
  {
    id: 'hplx', name: 'HPLX', type: 'Engine', status: 'In development', parent: null,
    summary: 'A modern reimplementation of a classic game engine. A foundation for bringing familiar worlds forward.',
    lead: 'Rebuilding the foundation.',
    overviewHeading: 'The engine behind the world.', connectionHeading: 'One foundation. Connected worlds.',
    connectionDescription: 'HPLX and Amnesia: The Dark Descent Redux are being developed together. Amnesia: A Machine for Pigs Redux is a second connected project; work on it has not started.',
    description: 'HPLX is an independent engine reimplementation project, starting with the foundations needed for Amnesia: The Dark Descent Redux.',
    art: 'engine.svg', artLabel: 'Original wireframe engine illustration',
    focus: 'Engine reimplementation',
    note: 'Work is in progress. There is no public release or download available here yet.',
    source: null,
  },
  {
    id: 'tdd', name: 'Amnesia: The Dark Descent Redux', shortName: 'TDD', type: 'Game reimplementation', status: 'In development', parent: 'hplx',
    summary: 'An independent reimplementation of Amnesia: The Dark Descent, built on HPLX.',
    lead: 'A familiar world. A new foundation.',
    overviewHeading: 'The world above the engine.', connectionHeading: 'Built on HPLX.',
    connectionDescription: 'The game and the engine are connected, with separate project pages so each can develop in its own direction.',
    legalNote: 'Independent reimplementation. Not an official release and not affiliated with or endorsed by the original game’s creators. Original names and assets belong to their respective owners.',
    description: 'Amnesia: The Dark Descent Redux is the first game reimplementation being developed alongside HPLX. It has its own project identity, with the engine underneath.',
    art: 'descent.svg', artLabel: 'Original abstract doorway illustration',
    focus: 'Game reimplementation',
    note: 'This project is in development. It is not a playable release, and no game assets or downloads are distributed here.',
    source: null,
  },
  {
    id: 'amfp', name: 'Amnesia: A Machine for Pigs Redux', shortName: 'AMFP', type: 'Game reimplementation', status: 'Not started', parent: 'hplx',
    parentRelationship: 'Planned on',
    summary: 'A planned independent reimplementation of Amnesia: A Machine for Pigs. Work has not started.',
    lead: 'A place for what comes later.',
    overviewHeading: 'Not started.', connectionHeading: 'Planned on HPLX.',
    connectionDescription: 'This project is listed alongside Amnesia: The Dark Descent Redux as a planned HPLX game reimplementation. Development has not begun.',
    legalNote: 'Planned independent reimplementation. Not an official release and not affiliated with or endorsed by the original game’s creators. Original names and assets belong to their respective owners.',
    description: 'Amnesia: A Machine for Pigs Redux is a planned project. This page records its place in the Cosmik catalog; work has not started.',
    art: null,
    focus: 'Game reimplementation',
    note: 'There are no implemented features, playable builds, downloads, or release dates announced here.',
    source: null,
  },
];
export const projectById = new Map(projects.map(project => [project.id, project]));
